// Code generated by goctl. DO NOT EDIT.
package types

type Request struct {
	Name string `json:"name"`
}

type Response struct {
	Message      string `json:"message"`
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	RefreshAfter int64  `json:"refreshAfter"`
}

type HouseReq struct {
	Area  string `form:"area"`
	Limit int64  `form:"limit,default=30"`
	Group string `form:"group,default=day"`
}

type HouseReply struct {
	XData         []string     `json:"xData"`
	YData         []int64      `json:"yData"`
	AreaRange     []AreaRange  `json:"areaRange"`
	AreaRangeData []string     `json:"areaRangeData"`
	LimitRange    []LimitRange `json:"limitRange"`
	GroupData     []GroupData  `json:"groupData"`
	SeriesData    []SeriesData `json:"seriesData"`
}

type AreaRange struct {
	Value string `json:"value"`
	Label string `json:"label"`
}

type LimitRange struct {
	Value int64 `json:"value"`
	Label int64 `json:"label"`
}

type GroupData struct {
	Value string `json:"value"`
	Label string `json:"label"`
}

type SeriesData struct {
	Name string  `json:"name"`
	Data []int64 `json:"data"`
	Type string  `json:"type"`
}
